console.log(typeof "Hello");  // "string"
console.log(typeof 123);   // "number"
console.log(typeof true); // "boolean"
console.log(typeof undefined);  // "undefined"
console.log(typeof null);// "object" 
console.log(typeof Symbol("id")); // "symbol"
console.log(typeof 123n);   // "bigint"
console.log(typeof Infinity); // "number"
console.log(typeof 'Welcome to JavaScript' / 5); // "NaN"
